apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
data:
  APP_KEY: YmFzZTY0Om41WmdYbGZOb01VQXV1cWJKN2dLRDcxRXJIUE9ORUhnL0l1QlJBVjZITG89
stringData:
  DB_USERNAME: laravel
  DB_PASSWORD: password
